name: Haskell application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.6'
          enable-stack: true
      - name: Run the file
        run: ./run.sh
